### ISSUE TITLE
gRPC and JSON RPC APIs improperly bound

### ISSUE THREAD

**Issue by thegoldenmule** [0xPolygon/polygon-edge#416]
### Description

Because both API servers are bound to `127.0.0.1`, neither function correctly when run inside a Docker container. Instead, they need to be bound to `0.0.0.0`.

### Your environment

* macOS Monterey, CentOS 7
* 0.2.1
* develop

### Steps to reproduce

I found this issue by trying to use `polygon-edge` with `docker-compose`. My `yml` file:

```
version: '3.9'
services:
  edge:
    image: 0xpolygon/polygon-edge:0.2.1
    ports:
      - "8545:8545"
    volumes:
      - /home/ec2-user/data:/blk
    working_dir: /blk
    command: polygon-edge server --data-dir /blk-node-1 --chain /blk/genesis.json --libp2p :10001 --seal --dev --log-level debug --access-control-allow-origins "*"
```

A simple `curl -X POST 'http://localhost:8545'` on the docker host will fail. To fix this, you can append this to the command:

```
--jsonrpc "0.0.0.0:8545"
```

### Expected behaviour

Simple `docker run 0xpolygon/polygon-edge` commands and `docker-compose` approaches should work out of the box.

### Actual behaviour

Running `polygon-edge` in a docker container defaults to a non-functional state.

### Proposed solution

The defaults in [`server_command.go`](https://github.com/0xPolygon/polygon-edge/blob/develop/command/server/server_command.go) should bind both grpc and json rpc addresses to all interfaces (`0.0.0.0`) instead of to loopback (`127.0.0.1`).

I would have made a PR, but this is a large change as `127.0.0.1` is copy/pasted throughout in comments and logs. I wanted to make sure this was the agreed upon approach before making the PR.
